language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: libnit.sln
jobs:
  include:
    - stage: build
      script: dotnet build -c release
    - stage: test
      script: dotnet test
    - stage: deploy
      if: branch = master
      script: dotnet pack -c release
